#variables:
#  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: gitlab-icarous-base:latest


before_script:
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo -e "$SWEE_SSHKEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - bash UpdateModules.sh
  - git submodule update --init --recursive apps/rotorsim/QuadCopterSim
  - git submodule update --init --recursive Python/PyIcarous
  - cd apps/rotorsim/QuadCopterSim && make
  - cd /builds/larc-nia-fm/icarous
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/builds/larc-nia-fm/icarous/Modules/lib
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/builds/larc-nia-fm/icarous/apps/rotorsim/QuadCopterSim
  - export PYTHONPATH=$PYTHONPATH:/builds/larc-nia-fm/icarous/apps/rotorsim/QuadCopterSim
  - sed -i s/arducopter/rotorsim/ Icarous_defs/apps.cmake
  - make 
  - make install
  
run-test:
  script:
    - cd Python/TestRunner
    - python3 RunScenarios.py scenarios.yaml --validate --test --verbose

