default:
  image: marcofeliu/icarous-base:latest


before_script:
  - git submodule update --init --recursive
  - make 
  - make install
  
run-test:
  script:
    - cd Python/TestRunner
    - python3 RunScenarios.py scenarios.yaml --test

